docs: Add installation guide to mkdocs
DSD-DBS/capella-collab-manager pull request #1053
Opened 2023-09-26 12:20 UTC by MoritzWeber0

There is also a less detailed installation guide in the README. These instructions should be merged in a later PR.

2023-09-26 12:22 UTC, Paula-Kli commented
Would it until it is merged with the readme be beneficial to add a hint in the readme to read the user docs for installation setup purposes? Maybe one sentence is enough but will make it a lot more discoverable

2023-09-27 14:53 UTC, Paula-Kli commented on README.md
> +The Installation Guide has been moved to the [general documentation](https://capella-collaboration-manager.readthedocs.io/en/latest/installation/).
```suggestion
You can find the installation guide for deployment in the [general documentation](https://capella-collaboration-manager.readthedocs.io/en/latest/installation/).
```

2023-09-27 14:54 UTC, Paula-Kli commented on docs/user/docs/installation.md
> +# Install the Collaboration Manager
```suggestion
# Installation of the Collaboration Manager
```

2023-09-27 15:13 UTC, Paula-Kli requested changes
I just read it and did not try it out so can not say whether I as a user would miss a step but I think it is really useful and very detailed 👍 Good docs

2023-09-27 15:13 UTC, Paula-Kli commented on docs/user/docs/installation.md
> +git clone https://github.com/DSD-DBS/capella-collab-manager.git
what about the docker-images submodule? that is not required because you use the docker images differently?

2023-09-27 15:13 UTC, Paula-Kli commented on docs/user/docs/installation.md
> +   ```
ah looks like you are cloning them later :D

2023-10-03 08:11 UTC, amolenaar approved these changes

2023-10-09 14:10 UTC, Paula-Kli commented on docs/user/docs/installation.md
> +to a persistent and secure location on your server or deploment environment.
```suggestion
to a persistent and secure location on your server or deployment environment.
```

2023-10-09 14:12 UTC, Paula-Kli approved these changes

2023-10-09 14:16 UTC, merged