feat: Unify various API endpoints related to config
DSD-DBS/capella-collab-manager pull request #2034
Opened 2024-11-25 14:28 UTC by zusorio

More details in the linked issue.

Closes #1960

2024-11-29 09:15 UTC, zusorio commented on backend/capellacollab/unifiedconfig/routes.py
> +    "/unified",
Change this to something more descriptive

2024-12-05 14:26 UTC, MoritzWeber0 requested changes

2024-12-05 14:26 UTC, MoritzWeber0 commented on backend/capellacollab/settings/configuration/routes.py
Since configuration got an integral part and is not only part of settings anymore, let's change the API route to `/configurations/unified` and the global configuration to `/configurations/global`

2024-12-05 14:26 UTC, MoritzWeber0 commented on backend/capellacollab/feedback/routes.py
>      "/feedback",
```suggestion
    "",
```

The feedback key can now be part of the parent `include_router` as prefix.

2024-12-05 14:26 UTC, MoritzWeber0 commented on backend/capellacollab/settings/configuration/unifiedconfig/util.py
> +    return global_config.beta
```suggestion
```

Those two functions are overkill and just add another layer of abstraction. Write out `global_config.beta` directly where it's used.

2024-12-05 14:26 UTC, MoritzWeber0 commented on backend/capellacollab/settings/configuration/unifiedconfig/__init__.py
I'd merge the `unified` module into the `configuration` module. It's not too large and highly interlinked.

2024-12-05 14:26 UTC, MoritzWeber0 commented on frontend/src/app/services/unified-config-wrapper/unified-config-wrapper.service.ts
> +  }
```suggestion
```

I'd prefer to keep the service simple in general and also remove all those different functions. If we add more and more, the service get's more messy. Instead, pipe the Observable in the components where they are actually used.

2024-12-05 14:26 UTC, MoritzWeber0 commented on frontend/src/app/users/users-profile/users-profile.component.html
> +  @if ((unifiedConfigWrapperService.beta$ | async)?.enabled) {
```suggestion
  @let betaConfig = (unifiedConfigWrapperService.unifiedConfig$ | async)?.beta;
  @if (betaConfig.enabled) {
```

2024-12-05 14:26 UTC, MoritzWeber0 commented on frontend/src/app/users/users-profile/users-profile.component.html
> +        (unifiedConfigWrapperService.beta$ | async)?.allow_self_enrollment)
```suggestion
        betaConfig.allow_self_enrollment)
```

2024-12-05 14:26 UTC, MoritzWeber0 commented on frontend/src/app/general/metadata/metadata.service.ts
> +  readonly backendMetadata = this.unifiedConfigWrapperService.metadata$;
```suggestion
```

Directly access the service in the template.

2024-12-06 11:57 UTC, MoritzWeber0 commented on frontend/src/app/sessions/feedback/feedback.service.ts
>    triggerFeedbackPrompt(): void {
The `triggerFeedbackPrompt` function is called directly after authentication is completed. At this time, the unified configuration is not loaded. Therefore, we should change it to use the Observable: 

```py
triggerFeedbackPrompt(): void {
    if (!this.authService.isLoggedIn()) return;
    this.feedbackConfig$.pipe(filter(Boolean), take(1)).subscribe((config) => {
      if (this.shouldShowIntervalPrompt(config)) {
        this.showDialog([], 'On interval');
        this.saveFeedbackPromptDate();
      }
    });
  }
```

2024-12-06 12:23 UTC, MoritzWeber0 approved these changes

2024-12-06 12:23 UTC, merged