V2/t4c instances
DSD-DBS/capella-collab-manager pull request #277
Opened 2022-10-04 14:02 UTC by TimoBbz

# Description

Handling of the t4c instances.

Resolves #issue

# Testing

How were the changes tested?

# Checklist

- [ ] My code follows the guidelines of this project: [CONTRIBUTING.md](/CONTRIBUTING.md)
- [ ] I updated the documentation with the new functionality
- [ ] I went through the code and removed all print statements, breakpoints and unused code
- [ ] Error handling for all possible scenarios has been implemented
- [ ] I've add logging for all relevant operations
- [ ] I added the appropriate labels to this PR (enhancement/bug/documentation, effort, priority)

2022-10-05 11:19 UTC, MoritzWeber0 requested changes
My suggested changes are in a separate PR: https://github.com/DSD-DBS/capella-collab-manager/pull/281

2022-10-05 14:15 UTC, MoritzWeber0 commented on frontend/src/app/settings/modelsources/t4c-settings/create-t4c-instance/create-t4c-instance.component.ts
> +          versions.filter((version: Version) => version.tool_id === 1)
Another solution could be to forbid the editing or removal of the tool with id 1.

2022-10-05 14:29 UTC, TimoBbz commented on frontend/src/app/settings/modelsources/t4c-settings/create-t4c-instance/create-t4c-instance.component.ts
> +          versions.filter((version: Version) => version.tool_id === 1)
Perhaps we could define a `VersionWithTool`, such as this:
```typescript
// service.ts

type VersionWithTool = Version & {
  tool: Tool,
}

get_versions_with_tool: Observable<VersionWithTool[]> () {
  return http.get<VersionWithTool[]>(url, {params: {withtool: true}});

// component.ts
this.toolService.get_versions_with_tool()
.pipe(
  filter(Boolean),
  map((versions =>
    versions.filter((version: VersionWithTool) => version.tool.name === "Capella")
  )
)
```

```python
# models.py
VersionWithTool(Version):
  tool: Tool

  class Config:
    orm_mode=True

# routes.py
@router.get('url')
def get_versions_with_tools(withtool: Boolean | None):
  if withtool:
    return [VersionWithTool(ver) for ver in crud.get_versions()]
```

2022-10-10 09:28 UTC, MoritzWeber0 approved these changes

2022-10-10 09:28 UTC, merged