Add CDO port to T4C instances.
DSD-DBS/capella-collab-manager pull request #361
Opened 2022-11-03 09:49 UTC by TimoBbz

# Description

The title tells all.

2022-11-08 14:43 UTC, MoritzWeber0 approved these changes
Great code here as well. But there will be a conflict in the frontend with #360. Can you rebase onto #360?

2022-11-09 06:47 UTC, MoritzWeber0 requested changes
We need another rebase, because you force pushed to #360 @TimoBbz

2022-11-09 08:54 UTC, TimoBbz commented
> We need another rebase, because you force pushed to #360 @TimoBbz

Are you sure? On my side the tree look like this, which is perfectly fine I think:
```
*   836959fe (origin/v2/staging, origin/HEAD, v2/staging) Merge pull request #360 from DSD-DBS/v2/persistent-session
|\
| | * 3fb8544d (HEAD -> v2/cdo-port, origin/v2/cdo-port) fix: Solve post-rebase Alembic issues.
| | * e7bef057 fix(front): Reorganise instance creation form fields.
| | * 55bcf508 fix: Make t4c model unique for repository and Capella model.
| | * 27258131 feat(front): Set default port for T4C instance.
| | * b37634fb fix(back): Validate ports in pydantic, make port required.
| | * 63f200a5 feat: Add CDO port to T4C instances.
| |/
| * 24668505 (origin/v2/persistent-session, v2/persistent-session) fix: Solve post-rebase Alembic issues.
```

2022-11-09 09:39 UTC, MoritzWeber0 approved these changes

2022-11-09 09:42 UTC, merged