Fix Github rate limiting during fetching of release notes in the pipeline
DSD-DBS/capella-collab-manager pull request #471
Opened 2022-12-16 15:11 UTC by MoritzWeber0

2022-12-16 15:14 UTC, amolenaar commented on .github/workflows/push.yml
> +          export GITHUB_USERNAME=GITHUB ACTIONS
```suggestion
          export GITHUB_USERNAME="GITHUB ACTIONS"
```

2022-12-16 15:15 UTC, amolenaar requested changes
Are those env vars really used?

2022-12-19 07:45 UTC, MoritzWeber0 commented
> Are those env vars really used?

They are used in `frontend/fetch-version.ts`.

2022-12-23 07:43 UTC, amolenaar approved these changes

2023-01-03 15:30 UTC, merged