Simplify release notes
DSD-DBS/capella-collab-manager pull request #472
Opened 2022-12-19 15:00 UTC by amolenaar

Simplify the release notes. Just link to a page in the docs (`/docs/release-notes`).

Removed Markdown component and configuration, since that was only used for rendering the release notes fetched from GH releases.

2022-12-20 08:13 UTC, dominik003 requested changes
Looks good except for two small things but how do we deal with the current versions that are not yet included in the release notes? Maybe we can put the old style release notes for the recent versions in the `release-notes.md` first or what is your option?

2022-12-20 08:13 UTC, dominik003 commented on frontend/src/app/general/metadata/version/version.component.html
> +  <a href="/docs/release-notes/" target="_blank">
I would probably also place the `<a>' around the *New version available ...* `<div>` because otherwise you can't click on it.

2023-01-05 13:01 UTC, MoritzWeber0 commented on docs/user/docs/release-notes.md
>   ~ SPDX-License-Identifier: Apache-2.0
I'd add a link to our Github releases page.

2023-01-05 13:15 UTC, MoritzWeber0 commented
This should be included as well: https://github.com/DSD-DBS/capella-collab-manager/issues/407

2023-01-05 15:42 UTC, merged