Replace MatLegacyDialog with MatDialog
DSD-DBS/capella-collab-manager pull request #561
Opened 2023-01-26 14:50 UTC by MoritzWeber0

2023-01-27 09:59 UTC, dominik003 requested changes
I think I have tried all the dialogs except the View Log dialog and added a comment to the dialogs where a padding/the dialog class is missing. Hopefully, I didn't miss one but in the worst case we have a dialog without a padding.

2023-01-27 09:59 UTC, dominik003 commented on frontend/src/app/sessions/active-sessions/file-browser/file-browser.component.html
> +<div>
The file browser component definitely misses some padding right now. So I think wrapping everything in a `div` with the `dialog` class would be sufficient here.

2023-01-27 09:59 UTC, dominik003 commented on frontend/src/app/sessions/new-readonly-session-dialog/new-readonly-session-dialog.component.html
>  <form (ngSubmit)="requestSession()">
In the `new-readonly-session-dialog.component.ts` the old `legacy-dialog` is still used and therefore requesting a readonly session is not possible right now. In addition, you need to add the `dialog` class here to add some padding to the dialog.

2023-01-27 09:59 UTC, dominik003 commented on frontend/src/app/projects/models/backup-settings/view-logs-dialog/view-logs-dialog.component.html
> +<div class="wrapper dialog">
In the `view-logs-dialog.component.ts` the legacy dialog is still used.

2023-01-27 09:59 UTC, dominik003 commented on frontend/src/app/settings/core/tools-settings/tool-details/tool-deletion-dialog/tool-deletion-dialog.component.html
> +<div>
```suggestion
<div class="dialog">
```
Similar to other dialogs, this dialogs misses some padding which should be solved by adding the `dialog` class to the div here.

2023-01-27 09:59 UTC, dominik003 commented on frontend/src/app/settings/modelsources/git-settings/delete-git-settings-dialog/delete-git-settings-dialog.component.html
> +<h1>Delete Instance {{ instance.name }}</h1>
This dialog misses some padding, so please put a div with the `dialog` class around it.

2023-01-27 09:59 UTC, dominik003 commented on frontend/src/app/settings/modelsources/t4c-settings/t4c-instance-settings/t4c-repo-deletion-dialog/t4c-repo-deletion-dialog.component.html
> -<h1 mat-dialog-title>Remove T4C repository</h1>
Please add a `div` with the `dialog` class here.

2023-02-02 17:21 UTC, MoritzWeber0 commented on frontend/src/app/projects/models/backup-settings/create-backup/create-backup.component.html
> +    >
Done.

2023-02-03 09:25 UTC, dominik003 approved these changes
It only needs a rebase and can then be merged

2023-02-03 10:23 UTC, merged