Backend monitoring
DSD-DBS/capella-collab-manager pull request #652
Opened 2023-03-13 15:56 UTC by amolenaar

Add monitoring for the backend.

The idea is that the backend can provide metrics regarding running sessions, and the session (deployment) state.

2023-03-29 07:00 UTC, MoritzWeber0 requested changes

2023-03-30 08:06 UTC, amolenaar commented on backend/capellacollab/__main__.py
> +        register_metrics,
True, this function was probably a left-over from some other approaches I tried.

2023-03-30 08:08 UTC, amolenaar commented on backend/capellacollab/sessions/metrics.py
> +        pods = operator.get_pods(label_selector=None)
This query is already reading all pods (in the sessions namespace), right?

2023-03-30 10:13 UTC, MoritzWeber0 commented on backend/capellacollab/sessions/metrics.py
> +        pods = operator.get_pods(label_selector=None)
`operator.get_pods` returns all pods in a namespace, not filtering for session Pods. The metrics endpoint for active sessions should just return session pods and no other pods.

2023-03-30 10:13 UTC, MoritzWeber0 commented on backend/capellacollab/__main__.py
> +        register_metrics,
Do you plan to remote it then?

2023-04-18 12:55 UTC, amolenaar commented on backend/capellacollab/sessions/metrics.py
> +        pods = operator.get_pods(label_selector=None)
![image](https://user-images.githubusercontent.com/96249/232783818-44ac6745-b1cd-4170-82cf-68294a73a318.png)

The metric now has a `workload` label, that tells us what kind of workload it is (session, job, cronjob)

2023-04-18 13:06 UTC, MoritzWeber0 approved these changes

2023-04-18 13:06 UTC, merged