Redesign project detail page
DSD-DBS/capella-collab-manager pull request #667
Opened 2023-03-31 11:55 UTC by MoritzWeber0

2023-04-03 12:44 UTC, MoritzWeber0 commented
Discussed in the Collab Manager planning, add are simplified version of Metadata (with description), only show forms when clicking on a "settings" icon.

2023-05-30 10:01 UTC, dominik003 requested changes
Looks good. I just found two issues that I solved in #724 and #725 that we should merge here before we merge this PR.

2023-06-01 09:53 UTC, MoritzWeber0 commented on frontend/src/app/app-routing.module.ts
> +          },
Fixed the routing structure with https://github.com/DSD-DBS/capella-collab-manager/pull/667/commits/902d6e53fc43273a00d663a993df60d1b774c63c

2023-06-01 10:20 UTC, dominik003 approved these changes

2023-06-01 10:21 UTC, merged