fix: Add asterisc to entry point when editiing the model sources
DSD-DBS/capella-collab-manager pull request #963
Opened 2023-08-23 10:43 UTC by Paula-Kli

Apparently the entrypoint field is not a required field in the strict sense since it has two error messages attached. Nevertheless, it confused me that it seems not to be required while at the same time throwing an error when being left empty.

2023-08-23 13:49 UTC, dominik003 requested changes
Good catch, but a provided a more proper fix for this problem as the entrypoint is not required for all of our model types.

2023-08-23 13:49 UTC, dominik003 commented on frontend/src/app/projects/models/model-source/git/manage-git-model/manage-git-model.component.html
Good catch there! However, simply adding the * here is not a proper fix. The star is automatically added to the label in case there is a required validator on the field. Therefore, the missing * indicates here that the field has not a required validator on it.
Furthermore, the entrypoint is not required for all models but just for *Capella* models (i.e., *Papyrus* and *Jupyter* models do not need an entrypoint).
So to properly fix this, you can change the following in the `manage-git-model.component.ts`:

Old:
```ts
this.form.controls.entrypoint.addValidators(
  Validators.pattern(/^$|\.aird$/),
);
```

New:
```ts
this.form.controls.entrypoint.addValidators([
  Validators.pattern(/^$|\.aird$/),
  Validators.required,
]);
```

2023-08-23 14:00 UTC, Paula-Kli commented on frontend/src/app/projects/models/model-source/git/manage-git-model/manage-git-model.component.html
ah ok I see - thanks for the explanation and the hint!

2023-08-23 14:51 UTC, dominik003 approved these changes

2023-09-05 12:51 UTC, MoritzWeber0 approved these changes

2023-09-05 12:51 UTC, merged